In [40]:
!pip install pandas
import pandas as pd

Requirement already satisfied: pandas in /Users/christiannogueras/opt/anaconda3/lib/python3.9/site-packages (1.4.2)
Requirement already satisfied: python-dateutil>=2.8.1 in /Users/christiannogueras/opt/anaconda3/lib/python3.9/site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /Users/christiannogueras/opt/anaconda3/lib/python3.9/site-packages (from pandas) (2021.3)
Requirement already satisfied: numpy>=1.18.5 in /Users/christiannogueras/opt/anaconda3/lib/python3.9/site-packages (from pandas) (1.21.5)
Requirement already satisfied: six>=1.5 in /Users/christiannogueras/opt/anaconda3/lib/python3.9/site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)

## Preprocessing

In [41]:
import pandas as pd
print('hello world')

####### Pre processing ######
df = pd.read_csv('Webull_Orders_Records-copy.csv')
df.sort_values(['Name', 'Side'], inplace=True)
# Filter cancelled orders
df = df[df['Filled'] > 0]
# df = df[df['Symbol'] == 'NNDM']
# df = df[df['Side'] == 'Sell']
df.drop(['Status', 'Filled', 'Avg Price', 'Time-in-Force',
        'Placed Time'], axis=1, inplace=True)

# remove @ on the price column and convert to numeric
df['Price'] = pd.to_numeric(df['Price'].str[1:], errors='raise')
df['Filled Time'] = pd.to_datetime(df['Filled Time'], errors='raise')

# put total
df['Total Price'] = df['Total Qty'] * df['Price']
df.to_csv('web2.csv')

######### doing analysis on data #########
currency = "${:,.2f}".format(df['Total Price'].sum())
print(currency)

buys = df[df['Side'] == 'Buy']
sells = df[df['Side'] == 'Sell']

print('buy')
print(buys.describe(include=['object']))

print('sell')
print(sells.describe(include=['object']))

# ######### Streamlit  ###########
# st.dataframe(df)

hello world
$42,295.80
buy
                  Name Symbol Side
count              299    299  299
unique              78     79    1
top     Nano Dimension   NNDM  Buy
freq                38     38  299
sell
               Name Symbol  Side
count           200    200   200
unique           80     81     1
top     fuboTV Inc.   FUBO  Sell
freq             17     17   200

/Users/christiannogueras/opt/anaconda3/lib/python3.9/site-packages/dateutil/parser/_parser.py:1207: UnknownTimezoneWarning: tzname EST identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.
  warnings.warn("tzname {tzname} identified but not understood.  "
/Users/christiannogueras/opt/anaconda3/lib/python3.9/site-packages/dateutil/parser/_parser.py:1207: UnknownTimezoneWarning: tzname EDT identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.
  warnings.warn("tzname {tzname} identified but not understood.  "

In [42]:
df

,Name,Symbol,Side,Total Qty,Price,Filled Time,Total Price
547,ALAMOS GOLD,AGI,Sell,1.0,0.02,2020-12-10 11:47:32,0.02
96,AMC Ent Holdg,AMC,Buy,1.0,56.60,2021-06-15 06:32:11,56.60
97,AMC Ent Holdg,AMC,Buy,3.0,56.00,2021-06-16 09:30:07,168.00
116,AMC Ent Holdg,AMC,Buy,4.0,50.28,2021-06-09 14:59:17,201.12
131,AMC Ent Holdg,AMC,Buy,2.0,56.95,2021-06-03 14:51:09,113.90
...,...,...,...,...,...,...,...
513,fuboTV Inc.,FUBO,Sell,1.0,9.97,2021-01-05 10:43:40,9.97
514,fuboTV Inc.,FUBO,Sell,1.0,9.74,2021-01-05 10:41:12,9.74
537,fuboTV Inc.,FUBO,Sell,1.0,3.80,2020-12-23 09:49:00,3.80
538,fuboTV Inc.,FUBO,Sell,4.0,9.00,2020-12-21 11:47:19,36.00
634,fuboTV Inc.,FUBO,Sell,1.0,27.41,2020-11-24 09:33:54,27.41

In [43]:
buys

,Name,Symbol,Side,Total Qty,Price,Filled Time,Total Price
96,AMC Ent Holdg,AMC,Buy,1.0,56.60,2021-06-15 06:32:11,56.60
97,AMC Ent Holdg,AMC,Buy,3.0,56.00,2021-06-16 09:30:07,168.00
116,AMC Ent Holdg,AMC,Buy,4.0,50.28,2021-06-09 14:59:17,201.12
131,AMC Ent Holdg,AMC,Buy,2.0,56.95,2021-06-03 14:51:09,113.90
155,AMC Ent Holdg,AMC,Buy,1.0,37.69,2021-06-02 09:30:13,37.69
...,...,...,...,...,...,...,...
470,fuboTV Inc.,FUBO,Buy,17.0,31.80,2021-01-20 09:34:37,540.60
523,fuboTV Inc.,FUBO,Buy,2.0,24.33,2021-01-04 14:34:33,48.66
595,fuboTV Inc.,FUBO,Buy,4.0,30.00,2020-12-01 16:36:25,120.00
607,fuboTV Inc.,FUBO,Buy,1.0,6.83,2020-11-27 12:54:00,6.83
689,fuboTV Inc.,FUBO,Buy,1.0,21.40,2020-11-19 08:09:08,21.40

In [44]:
sells

,Name,Symbol,Side,Total Qty,Price,Filled Time,Total Price
547,ALAMOS GOLD,AGI,Sell,1.0,0.02,2020-12-10 11:47:32,0.02
95,AMC Ent Holdg,AMC,Sell,4.0,54.88,2021-06-16 09:46:46,219.52
117,AMC Ent Holdg,AMC,Sell,4.0,40.00,2021-06-10 12:14:17,160.00
132,AMC Ent Holdg,AMC,Sell,2.0,48.75,2021-06-04 09:30:03,97.50
154,AMC Ent Holdg,AMC,Sell,1.0,60.27,2021-06-02 12:26:05,60.27
...,...,...,...,...,...,...,...
513,fuboTV Inc.,FUBO,Sell,1.0,9.97,2021-01-05 10:43:40,9.97
514,fuboTV Inc.,FUBO,Sell,1.0,9.74,2021-01-05 10:41:12,9.74
537,fuboTV Inc.,FUBO,Sell,1.0,3.80,2020-12-23 09:49:00,3.80
538,fuboTV Inc.,FUBO,Sell,4.0,9.00,2020-12-21 11:47:19,36.00
634,fuboTV Inc.,FUBO,Sell,1.0,27.41,2020-11-24 09:33:54,27.41

## Profit on a stock

In [79]:
stockSymbol = 'NIO'
stockSerie = buys[buys['Symbol'] == stockSymbol]

In [80]:
totalBuys = stockSerie['Total Price'].sum()
totalBuys

2396.1100000000006

In [81]:
nanoSells = sells[sells['Symbol'] == stockSymbol]
totalSells = nanoSells['Total Price'].sum()
totalSells

3311.3300000000004

In [82]:
profit = totalBuys - totalSells
profit

-915.2199999999998

## Plot

In [78]:
stocks = df
stocks

,Name,Symbol,Side,Total Qty,Price,Filled Time,Total Price
547,ALAMOS GOLD,AGI,Sell,1.0,0.02,2020-12-10 11:47:32,0.02
96,AMC Ent Holdg,AMC,Buy,1.0,56.60,2021-06-15 06:32:11,56.60
97,AMC Ent Holdg,AMC,Buy,3.0,56.00,2021-06-16 09:30:07,168.00
116,AMC Ent Holdg,AMC,Buy,4.0,50.28,2021-06-09 14:59:17,201.12
131,AMC Ent Holdg,AMC,Buy,2.0,56.95,2021-06-03 14:51:09,113.90
...,...,...,...,...,...,...,...
513,fuboTV Inc.,FUBO,Sell,1.0,9.97,2021-01-05 10:43:40,9.97
514,fuboTV Inc.,FUBO,Sell,1.0,9.74,2021-01-05 10:41:12,9.74
537,fuboTV Inc.,FUBO,Sell,1.0,3.80,2020-12-23 09:49:00,3.80
538,fuboTV Inc.,FUBO,Sell,4.0,9.00,2020-12-21 11:47:19,36.00
634,fuboTV Inc.,FUBO,Sell,1.0,27.41,2020-11-24 09:33:54,27.41